title: xxxkang's GitHub Pages Toy
author: xxxkang
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This website is created for the sole purpose of exploring functionalities of
  GitHub Pages.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
